blackfin: provide section reference work around helper
When sections are referenced in C code but no linker script
reference is explicitly used gcc on blackfin seems to not
provide a backward map to symbols, so a work around is
needed providing direct mapping.

This will be needed later when section ranges and linker table
support is added. Section ranges and linker tables enable adding
custom section code without the need for a respective linker
script modification.

Without this, for instance, with:

CONFIG_FIRMWARE_IN_KERNEL=y
CONFIG_DYNAMIC_DEBUG=y

we end up with:

  LD      init/built-in.o
lib/built-in.o: In function `dynamic_debug_init':
lib/dynamic_debug.c:(.init.text+0x158): undefined reference to `__verbose__end'
lib/dynamic_debug.c:(.init.text+0x15c): undefined reference to `__verbose__end'
lib/dynamic_debug.c:(.init.text+0x160): undefined reference to `__verbose'
lib/dynamic_debug.c:(.init.text+0x166): undefined reference to `__verbose'
lib/dynamic_debug.c:(.init.text+0x1a0): undefined reference to `__verbose__end'
lib/dynamic_debug.c:(.init.text+0x1a4): undefined reference to `__verbose__end'
lib/dynamic_debug.c:(.init.text+0x23e): undefined reference to `__verbose__end'
lib/dynamic_debug.c:(.init.text+0x244): undefined reference to `__verbose__end'
drivers/built-in.o: In function `release_firmware': (.text+0x23d5a): undefined reference to `builtin_fw'
drivers/built-in.o: In function `release_firmware': (.text+0x23d5e): undefined reference to `builtin_fw__end'
drivers/built-in.o: In function `release_firmware': (.text+0x23d62): undefined reference to `builtin_fw'
drivers/built-in.o: In function `release_firmware': (.text+0x23d66): undefined reference to `builtin_fw__end'
drivers/built-in.o: In function `_request_firmware':
drivers/base/firmware_class.c:(.text+0x240e2): undefined reference to `builtin_fw'
drivers/base/firmware_class.c:(.text+0x240e6): undefined reference to `builtin_fw__end'
drivers/base/firmware_class.c:(.text+0x240ea): undefined reference to `builtin_fw'
drivers/base/firmware_class.c:(.text+0x240ee): undefined reference to `builtin_fw__end'
drivers/built-in.o: In function `device_uncache_fw_images_work':
drivers/base/firmware_class.c:(.text+0x248a8): undefined reference to `builtin_fw'
drivers/base/firmware_class.c:(.text+0x248ac): undefined reference to `builtin_fw__end'
drivers/base/firmware_class.c:(.text+0x248b0): undefined reference to `builtin_fw'
drivers/base/firmware_class.c:(.text+0x248b4): undefined reference to `builtin_fw__end'
drivers/base/firmware_class.c:(.text+0x248e4): undefined reference to `builtin_fw'
drivers/base/firmware_class.c:(.text+0x248e8): undefined reference to `builtin_fw'
Makefile:956: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

This happens with gcc gcc-5.3.0 and binutils 2.27.51.20160730.
This fixes this issue. For further inspection check:

/opt/cross-gcc-5.3.0/bin/bfin-elf-objdump -x drivers/base/firmware_class.o | grep builtin
 17 .rodata.tbl.builtin_fw.~ 00000000  00000000  00000000  00001540 2**2
 18 .rodata.tbl.builtin_fw. 00000000  00000000  00000000  00001540  2**2
00000000 l    d  .rodata.tbl.builtin_fw.~       00000000 .rodata.tbl.builtin_fw.~
00000000 l    d  .rodata.tbl.builtin_fw.        00000000 .rodata.tbl.builtin_fw.
00000000         *UND*  00000000 _builtin_fw
00000000         *UND*  00000000 _builtin_fw__end
00000000 g     O .rodata.tbl.builtin_fw.~       00000000 __builtin_fw__end
00000000  w    O .rodata.tbl.builtin_fw.        00000000 __builtin_fw
00000252 R_BFIN_HUIMM16    _builtin_fw
00000256 R_BFIN_HUIMM16    _builtin_fw__end
0000025a R_BFIN_LUIMM16    _builtin_fw
0000025e R_BFIN_LUIMM16    _builtin_fw__end
000005da R_BFIN_HUIMM16    _builtin_fw
000005de R_BFIN_HUIMM16    _builtin_fw__end
000005e2 R_BFIN_LUIMM16    _builtin_fw
000005e6 R_BFIN_LUIMM16    _builtin_fw__end
00000da0 R_BFIN_HUIMM16    _builtin_fw
00000da4 R_BFIN_HUIMM16    _builtin_fw__end
00000da8 R_BFIN_LUIMM16    _builtin_fw
00000dac R_BFIN_LUIMM16    _builtin_fw__end
00000ddc R_BFIN_HUIMM16    _builtin_fw
00000de0 R_BFIN_LUIMM16    _builtin_fw

Then also:
/opt/cross-gcc-5.3.0/bin/bfin-elf-objdump -x -j .rodata.tbl.builtin_fw.~ drivers/base/firmware_class.o

drivers/base/firmware_class.o:     file format elf32-bfin
drivers/base/firmware_class.o
architecture: bfin, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x00000000
private flags = 0:

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
 17 .rodata.tbl.builtin_fw.~ 00000000  00000000  00000000  00001540 2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
SYMBOL TABLE:
00000000 l    d  .rodata.tbl.builtin_fw.~       00000000 .rodata.tbl.builtin_fw.~
00000000 g     O .rodata.tbl.builtin_fw.~       00000000 __builtin_fw__end

Cc: Barry Song <barry.song@analog.com>
Cc: Mike Frysinger <vapier@gentoo.org>
Cc: Steven Miao <realmz6@gmail.com>
Cc: Michael Matz <matz@suse.de>
Cc: Guenter Roeck <linux@roeck-us.net>
Cc: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Luis R. Rodriguez <mcgrof@kernel.org>